language: php

php:
    - 8.1
    - 8.2

before_install:
    - curl -s https://getcomposer.org/installer | php
    - composer req roave/security-advisories:dev-master --no-update
    - composer install

script:
    - php -v
    - vendor/bin/phpcs
    - vendor/bin/phpstan
    - vendor/bin/phpunit

after_success:
    - bash <(curl -s https://codecov.io/bash)
